// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type = component.MustNewType("googlecloudlogging")
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
